namespace Gl;

using System;

[Flags]
public enum BufferBit {
    DEPTH_BUFFER_BIT = Const.GL_DEPTH_BUFFER_BIT,
    ACCUM_BUFFER_BIT = Const.GL_ACCUM_BUFFER_BIT,
    STENCIL_BUFFER_BIT = Const.GL_STENCIL_BUFFER_BIT,
    COLOR_BUFFER_BIT = Const.GL_COLOR_BUFFER_BIT,
    ColorDepth = COLOR_BUFFER_BIT  | DEPTH_BUFFER_BIT,
}
