namespace Gl;

public enum BufferTarget {
    PARAMETER_BUFFER = Const.GL_PARAMETER_BUFFER,
    ARRAY_BUFFER = Const.GL_ARRAY_BUFFER,
    ELEMENT_ARRAY_BUFFER = Const.GL_ELEMENT_ARRAY_BUFFER,
    PIXEL_PACK_BUFFER = Const.GL_PIXEL_PACK_BUFFER,
    PIXEL_UNPACK_BUFFER = Const.GL_PIXEL_UNPACK_BUFFER,
    UNIFORM_BUFFER = Const.GL_UNIFORM_BUFFER,
    TEXTURE_BUFFER = Const.GL_TEXTURE_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER = Const.GL_TRANSFORM_FEEDBACK_BUFFER,
    COPY_READ_BUFFER = Const.GL_COPY_READ_BUFFER,
    COPY_WRITE_BUFFER = Const.GL_COPY_WRITE_BUFFER,
    DRAW_INDIRECT_BUFFER = Const.GL_DRAW_INDIRECT_BUFFER,
    SHADER_STORAGE_BUFFER = Const.GL_SHADER_STORAGE_BUFFER,
    DISPATCH_INDIRECT_BUFFER = Const.GL_DISPATCH_INDIRECT_BUFFER,
    QUERY_BUFFER = Const.GL_QUERY_BUFFER,
    ATOMIC_COUNTER_BUFFER = Const.GL_ATOMIC_COUNTER_BUFFER,
}
