namespace Gl;
using System;
[Flags]
public enum BufferStorageMask {
    DYNAMIC_STORAGE_BIT = Const.GL_DYNAMIC_STORAGE_BIT,
    //DYNAMIC_STORAGE_BIT_EXT = Const.GL_DYNAMIC_STORAGE_BIT_EXT,
    CLIENT_STORAGE_BIT = Const.GL_CLIENT_STORAGE_BIT,
    //CLIENT_STORAGE_BIT_EXT = Const.GL_CLIENT_STORAGE_BIT_EXT,
    SPARSE_STORAGE_BIT_ARB = Const.GL_SPARSE_STORAGE_BIT_ARB,
    LGPU_SEPARATE_STORAGE_BIT_NVX = Const.GL_LGPU_SEPARATE_STORAGE_BIT_NVX,
    PER_GPU_STORAGE_BIT_NV = Const.GL_PER_GPU_STORAGE_BIT_NV,
    EXTERNAL_STORAGE_BIT_NVX = Const.GL_EXTERNAL_STORAGE_BIT_NVX,
    MAP_READ_BIT = Const.GL_MAP_READ_BIT,
    //MAP_READ_BIT_EXT = Const.GL_MAP_READ_BIT_EXT,
    MAP_WRITE_BIT = Const.GL_MAP_WRITE_BIT,
    //MAP_WRITE_BIT_EXT = Const.GL_MAP_WRITE_BIT_EXT,
    MAP_PERSISTENT_BIT = Const.GL_MAP_PERSISTENT_BIT,
    //MAP_PERSISTENT_BIT_EXT = Const.GL_MAP_PERSISTENT_BIT_EXT,
    MAP_COHERENT_BIT = Const.GL_MAP_COHERENT_BIT,
    //MAP_COHERENT_BIT_EXT = Const.GL_MAP_COHERENT_BIT_EXT,
}
