namespace Gl;

public enum FramebufferTarget {
    READ_FRAMEBUFFER = Const.GL_READ_FRAMEBUFFER,
    DRAW_FRAMEBUFFER = Const.GL_DRAW_FRAMEBUFFER,
    FRAMEBUFFER = Const.GL_FRAMEBUFFER,
    //FRAMEBUFFER_OES = Const.GL_FRAMEBUFFER_OES,
}
