namespace Gl;

public enum FramebufferStatus {
    Error = 0,
    FRAMEBUFFER_UNDEFINED = Const.GL_FRAMEBUFFER_UNDEFINED,
    FRAMEBUFFER_COMPLETE = Const.GL_FRAMEBUFFER_COMPLETE,
    FRAMEBUFFER_INCOMPLETE_ATTACHMENT = Const.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT,
    FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = Const.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT,
    FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = Const.GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER,
    FRAMEBUFFER_INCOMPLETE_READ_BUFFER = Const.GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER,
    FRAMEBUFFER_UNSUPPORTED = Const.GL_FRAMEBUFFER_UNSUPPORTED,
    FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = Const.GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE,
    FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = Const.GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS,
}
