namespace Gl;

public enum GlErrorCode {
    NO_ERROR = Const.GL_NO_ERROR,
    INVALID_ENUM = Const.GL_INVALID_ENUM,
    INVALID_VALUE = Const.GL_INVALID_VALUE,
    INVALID_OPERATION = Const.GL_INVALID_OPERATION,
    STACK_OVERFLOW = Const.GL_STACK_OVERFLOW,
    STACK_UNDERFLOW = Const.GL_STACK_UNDERFLOW,
    OUT_OF_MEMORY = Const.GL_OUT_OF_MEMORY,
    INVALID_FRAMEBUFFER_OPERATION = Const.GL_INVALID_FRAMEBUFFER_OPERATION,
    //INVALID_FRAMEBUFFER_OPERATION_EXT = Const.GL_INVALID_FRAMEBUFFER_OPERATION_EXT,
    //INVALID_FRAMEBUFFER_OPERATION_OES = Const.GL_INVALID_FRAMEBUFFER_OPERATION_OES,
    //TABLE_TOO_LARGE_EXT = Const.GL_TABLE_TOO_LARGE_EXT,
    TABLE_TOO_LARGE = Const.GL_TABLE_TOO_LARGE,
    TEXTURE_TOO_LARGE_EXT = Const.GL_TEXTURE_TOO_LARGE_EXT,
}
