namespace Gl;

public enum ProgramProperty {
    COMPUTE_WORK_GROUP_SIZE = Const.GL_COMPUTE_WORK_GROUP_SIZE,
    PROGRAM_BINARY_LENGTH = Const.GL_PROGRAM_BINARY_LENGTH,
    GEOMETRY_VERTICES_OUT = Const.GL_GEOMETRY_VERTICES_OUT,
    GEOMETRY_INPUT_TYPE = Const.GL_GEOMETRY_INPUT_TYPE,
    GEOMETRY_OUTPUT_TYPE = Const.GL_GEOMETRY_OUTPUT_TYPE,
    ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = Const.GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH,
    ACTIVE_UNIFORM_BLOCKS = Const.GL_ACTIVE_UNIFORM_BLOCKS,
    DELETE_STATUS = Const.GL_DELETE_STATUS,
    LINK_STATUS = Const.GL_LINK_STATUS,
    VALIDATE_STATUS = Const.GL_VALIDATE_STATUS,
    INFO_LOG_LENGTH = Const.GL_INFO_LOG_LENGTH,
    ATTACHED_SHADERS = Const.GL_ATTACHED_SHADERS,
    ACTIVE_UNIFORMS = Const.GL_ACTIVE_UNIFORMS,
    ACTIVE_UNIFORM_MAX_LENGTH = Const.GL_ACTIVE_UNIFORM_MAX_LENGTH,
    ACTIVE_ATTRIBUTES = Const.GL_ACTIVE_ATTRIBUTES,
    ACTIVE_ATTRIBUTE_MAX_LENGTH = Const.GL_ACTIVE_ATTRIBUTE_MAX_LENGTH,
    TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = Const.GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH,
    TRANSFORM_FEEDBACK_BUFFER_MODE = Const.GL_TRANSFORM_FEEDBACK_BUFFER_MODE,
    TRANSFORM_FEEDBACK_VARYINGS = Const.GL_TRANSFORM_FEEDBACK_VARYINGS,
    ACTIVE_ATOMIC_COUNTER_BUFFERS = Const.GL_ACTIVE_ATOMIC_COUNTER_BUFFERS,
}
