namespace Gl;

public enum ProgramInterface {
    TRANSFORM_FEEDBACK_BUFFER = Const.GL_TRANSFORM_FEEDBACK_BUFFER,
    UNIFORM = Const.GL_UNIFORM,
    UNIFORM_BLOCK = Const.GL_UNIFORM_BLOCK,
    PROGRAM_INPUT = Const.GL_PROGRAM_INPUT,
    PROGRAM_OUTPUT = Const.GL_PROGRAM_OUTPUT,
    BUFFER_VARIABLE = Const.GL_BUFFER_VARIABLE,
    SHADER_STORAGE_BLOCK = Const.GL_SHADER_STORAGE_BLOCK,
    VERTEX_SUBROUTINE = Const.GL_VERTEX_SUBROUTINE,
    TESS_CONTROL_SUBROUTINE = Const.GL_TESS_CONTROL_SUBROUTINE,
    TESS_EVALUATION_SUBROUTINE = Const.GL_TESS_EVALUATION_SUBROUTINE,
    GEOMETRY_SUBROUTINE = Const.GL_GEOMETRY_SUBROUTINE,
    FRAGMENT_SUBROUTINE = Const.GL_FRAGMENT_SUBROUTINE,
    COMPUTE_SUBROUTINE = Const.GL_COMPUTE_SUBROUTINE,
    VERTEX_SUBROUTINE_UNIFORM = Const.GL_VERTEX_SUBROUTINE_UNIFORM,
    TESS_CONTROL_SUBROUTINE_UNIFORM = Const.GL_TESS_CONTROL_SUBROUTINE_UNIFORM,
    TESS_EVALUATION_SUBROUTINE_UNIFORM = Const.GL_TESS_EVALUATION_SUBROUTINE_UNIFORM,
    GEOMETRY_SUBROUTINE_UNIFORM = Const.GL_GEOMETRY_SUBROUTINE_UNIFORM,
    FRAGMENT_SUBROUTINE_UNIFORM = Const.GL_FRAGMENT_SUBROUTINE_UNIFORM,
    COMPUTE_SUBROUTINE_UNIFORM = Const.GL_COMPUTE_SUBROUTINE_UNIFORM,
    TRANSFORM_FEEDBACK_VARYING = Const.GL_TRANSFORM_FEEDBACK_VARYING,
}
