namespace Gl;

public enum ProgramInterfaceParameter {
    ACTIVE_RESOURCES = Const.GL_ACTIVE_RESOURCES,
    MAX_NAME_LENGTH = Const.GL_MAX_NAME_LENGTH,
    MAX_NUM_ACTIVE_VARIABLES = Const.GL_MAX_NUM_ACTIVE_VARIABLES,
    MAX_NUM_COMPATIBLE_SUBROUTINES = Const.GL_MAX_NUM_COMPATIBLE_SUBROUTINES,
}
