namespace Gl;

public enum ShaderType {
    FRAGMENT_SHADER = Const.GL_FRAGMENT_SHADER,
    //FRAGMENT_SHADER_ARB = Const.GL_FRAGMENT_SHADER_ARB,
    VERTEX_SHADER = Const.GL_VERTEX_SHADER,
    //VERTEX_SHADER_ARB = Const.GL_VERTEX_SHADER_ARB,
    GEOMETRY_SHADER = Const.GL_GEOMETRY_SHADER,
    TESS_EVALUATION_SHADER = Const.GL_TESS_EVALUATION_SHADER,
    TESS_CONTROL_SHADER = Const.GL_TESS_CONTROL_SHADER,
    COMPUTE_SHADER = Const.GL_COMPUTE_SHADER,
}
