namespace Gl;

public enum UniformType {
    Double = Const.DOUBLE,
    Float = Const.FLOAT,
    Int = Const.INT,
    Mat2d = Const.DOUBLE_MAT2,
    Mat2x3 = Const.FLOAT_MAT2x3,
    Mat2x3d = Const.DOUBLE_MAT2x3,
    Mat2x4 = Const.FLOAT_MAT2x4,
    Mat2x4d = Const.DOUBLE_MAT2x4,
    Mat3d = Const.DOUBLE_MAT3,
    Mat3x2 = Const.FLOAT_MAT3x2,
    Mat3x2d = Const.DOUBLE_MAT3x2,
    Mat3x4 = Const.FLOAT_MAT3x4,
    Mat3x4d = Const.DOUBLE_MAT3x4,
    Mat4d = Const.DOUBLE_MAT4,
    Mat4x2 = Const.FLOAT_MAT4x2,
    Mat4x2d = Const.DOUBLE_MAT4x2,
    Mat4x3 = Const.FLOAT_MAT4x3,
    Mat4x3d = Const.DOUBLE_MAT4x3,
    Matrix2x2 = Const.FLOAT_MAT2,
    Matrix3x3 = Const.FLOAT_MAT3,
    Matrix4x4 = Const.FLOAT_MAT4,
    Sampler2D = Const.SAMPLER_2D,
    UInt = Const.UNSIGNED_INT,
    Vec2d = Const.DOUBLE_VEC2,
    Vec2ui = Const.UNSIGNED_INT_VEC2,
    Vec3d = Const.DOUBLE_VEC3,
    Vec3ui = Const.UNSIGNED_INT_VEC3,
    Vec4d = Const.DOUBLE_VEC4,
    Vec4ui = Const.UNSIGNED_INT_VEC4,
    Vector2 = Const.FLOAT_VEC2,
    Vector2i = Const.INT_VEC2,
    Vector3 = Const.FLOAT_VEC3,
    Vector3i = Const.INT_VEC3,
    Vector4 = Const.FLOAT_VEC4,
    Vector4i = Const.INT_VEC4,
}
