namespace Gl;

public enum UniformBlockPName {
    UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER,
    UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER,
    UNIFORM_BLOCK_BINDING = Const.GL_UNIFORM_BLOCK_BINDING,
    UNIFORM_BLOCK_DATA_SIZE = Const.GL_UNIFORM_BLOCK_DATA_SIZE,
    UNIFORM_BLOCK_NAME_LENGTH = Const.GL_UNIFORM_BLOCK_NAME_LENGTH,
    UNIFORM_BLOCK_ACTIVE_UNIFORMS = Const.GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS,
    UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = Const.GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES,
    UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER,
    UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER,
    UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER,
    UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = Const.GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER,
}
