namespace Gl;

public enum VertexAttribPointerType {
    BYTE = Const.GL_BYTE,
    UNSIGNED_BYTE = Const.GL_UNSIGNED_BYTE,
    SHORT = Const.GL_SHORT,
    UNSIGNED_SHORT = Const.GL_UNSIGNED_SHORT,
    INT = Const.GL_INT,
    UNSIGNED_INT = Const.GL_UNSIGNED_INT,
    FLOAT = Const.GL_FLOAT,
    DOUBLE = Const.GL_DOUBLE,
    HALF_FLOAT = Const.GL_HALF_FLOAT,
    FIXED = Const.GL_FIXED,
    INT64_ARB = Const.GL_INT64_ARB,
    INT64_NV = Const.GL_INT64_NV,
    UNSIGNED_INT64_ARB = Const.GL_UNSIGNED_INT64_ARB,
    UNSIGNED_INT64_NV = Const.GL_UNSIGNED_INT64_NV,
    UNSIGNED_INT_2_10_10_10_REV = Const.GL_UNSIGNED_INT_2_10_10_10_REV,
    //UNSIGNED_INT_2_10_10_10_REV_EXT = Const.GL_UNSIGNED_INT_2_10_10_10_REV_EXT,
    UNSIGNED_INT_10F_11F_11F_REV = Const.GL_UNSIGNED_INT_10F_11F_11F_REV,
    INT_2_10_10_10_REV = Const.GL_INT_2_10_10_10_REV,
}
