<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Deterministic>true</Deterministic>
        <LangVersion>preview</LangVersion>
        <NoWarn>1701;1702;CS0078</NoWarn>
        <Nullable>disable</Nullable>
        <OutputType>library</OutputType>
        <ProduceReferenceAssemblies>false</ProduceReferenceAssemblies>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <TargetFramework>net9.0-windows</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>DEBUG;TRACE;</DefineConstants>
        <Optimize>false</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
    </PropertyGroup>
</Project>
